-- MySQL Script generated by MySQL Workbench
-- Mon May 24 22:52:25 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema kylcth9tthkbezgd
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema kylcth9tthkbezgd
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `kylcth9tthkbezgd` DEFAULT CHARACTER SET utf8 ;
USE `kylcth9tthkbezgd` ;

-- -----------------------------------------------------
-- Table `kylcth9tthkbezgd`.`registro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kylcth9tthkbezgd`.`registro` (
  `idregistro` INT NOT NULL,
  `placa` VARCHAR(10) NOT NULL,
  `fecha` TIMESTAMP NOT NULL,
  PRIMARY KEY (`idregistro`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
