-- MySQL Script generated by MySQL Workbench
-- Mon May 31 19:06:01 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema kylcth9tthkbezgd
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema kylcth9tthkbezgd
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `kylcth9tthkbezgd` DEFAULT CHARACTER SET utf8 ;
USE `kylcth9tthkbezgd` ;

-- -----------------------------------------------------
-- Table `kylcth9tthkbezgd`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kylcth9tthkbezgd`.`usuario` (
  `idusuario` INT NOT NULL AUTO_INCREMENT,
  `nombreUsuario` VARCHAR(45) NOT NULL,
  `contrasena` VARCHAR(254) NOT NULL,
  `nombreEstacion` VARCHAR(254) NOT NULL,
  `estado` INT NOT NULL DEFAULT 0,
  `rol` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`idusuario`),
  UNIQUE INDEX `nombreUsuario_UNIQUE` (`nombreUsuario` ASC) VISIBLE,
  UNIQUE INDEX `nombreEstacion_UNIQUE` (`nombreEstacion` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kylcth9tthkbezgd`.`registro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kylcth9tthkbezgd`.`registro` (
  `idregistro` INT NOT NULL AUTO_INCREMENT,
  `placa` VARCHAR(10) NOT NULL,
  `fecha` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `fkUsuario` INT NOT NULL,
  PRIMARY KEY (`idregistro`),
  INDEX `fk_registro_usuario_idx` (`fkUsuario` ASC) VISIBLE,
  CONSTRAINT `fk_registro_usuario`
    FOREIGN KEY (`fkUsuario`)
    REFERENCES `kylcth9tthkbezgd`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
